### ISSUE TITLE
test.sh erro

### ISSUE THREAD

**Issue by wowfee** [RUBi-ZA/MD-TASK#31]
hello , i correctly install the software,when i run test.sh it has erro with :
![image](https://user-images.githubusercontent.com/47892217/76047689-80e23000-5f9e-11ea-977f-a7ef1b0bffa0.png)
is there any operate wrong? could anyone give suggestions? 
thank you very much!

**Comment by oliserand** [comment]
Hi feijunwen,

It's likely that it's using you ran the test twice and you might be using another Python environment instead of the one created in the venv directory. We have plans to gradually port the code to Python 3 - we're not sure for when.

Try deleting the directory "out_BC" first, and running the command "source venv/bin/activate" under the MD-TASK directory before calculating the dynamic networks.

**Comment by michaelglenister** [comment]
Just an update to this, branch 1.2.x of MD-TASK should be Python 3 compatible and will be merged to the master branch in the near future. I suggest you try 1.2.x and let us know if you come across any issues

You can clone specific branches with this command:

git clone --single-branch --branch 1.2.x https://github.com/RUBi-ZA/MD-TASK.git

**Comment by wowfee** [comment]
Thank you very much! i use the 1.2X then there is no problem!
