### ISSUE TITLE
Not able to run Network analysis ( Average Shortest Path(L) calculation) 

### ISSUE THREAD

**Issue by hypowergravity** [RUBi-ZA/MD-TASK#33]
Hello, 
I am getting the following error while calculating the Average Shortest Path(L) calculation while running MD-Task, for my trajectory, even for the test case I am getting the following error, I have installed the MD-Task in ubuntu 20.10 version, mdtraj(1.9.5) 
###########
calc_network.py --ligands resname1:TMN,resname2:2G1 --topology average.pdb 500ns_1ns_tr.xtc --threshold 5.0 --calc-L --discard-graphs --step 100
INFO::Started at: 2021-04-28 17:10:42.532004
INFO::Calculating shortest paths...
ERROR::type=general:frame=1:message='generator' object is not subscriptable
ERROR::type=general:frame=2:message='generator' object is not subscriptable
ERROR::type=general:frame=3:message='generator' object is not subscriptable
ERROR::type=general:frame=4:message='generator' object is not subscriptable
ERROR::type=general:frame=5:message='generator' object is not subscriptable
ERROR::type=general:frame=6:message='generator' object is not subscriptable
INFO::Completed at: 2021-04-28 17:11:03.943481
INFO::- Total time: 0:00:21
########
Kingly please help me resolve the issue.
Thank you.

**Comment by oliserand** [comment]
Dear Sriram,

Thanks for using MD-TASK. Can you please try a cut-off of 6.7 instead of 5
(as we're using coarse grained protein residues - we're not using the full
sidechain) to decrease the possibility of having unconnected components in
the graph. If you wish to include a ligand atom, the ligand specification
has to look something like that:* "--ligand TMN:C1" *to specify the C1 atom
from the TMN ligand residue. Let me know how it works out, otherwise you
can send us a sample of your input data.

Kind regards,
Olivier

**Comment by hypowergravity** [comment]
Dear Oliver,
Thank you for the reply, It worked.

With Regards

S.Sriram
