### ISSUE TITLE
contact_map.py : "Chain label not found in topology file"

### ISSUE THREAD

**Issue by cpayal** [RUBi-ZA/MD-TASK#43]
Hi 

While using contact_map.py, I am using the following command:

`!contact_map.py --topology mutant_reduced_gmx.pdb --step 10 --residue SER698 --ocsv SER698_mutant.csv mutant_reduced.trr`

I used `trjconv` to write the last frame of my trajectory to a pdb `mutant_reduced_gmx.pdb` . My pdb originally does not have a chain ID, however even after I put one in it, I see the following error:

`ValueError: ERROR: Chain label not found in topology file. It cannot be empty.`

I have also converted my gro to pdb in VMD, but still see the same error. 

Thanks
Payal

**Comment by oliserand** [comment]
Hi @cpayal. Please check if the chain label for the PDB file is at character position 22 (i.e. index 21) for each ATOM entry. Or, compare it against a [PDB file](https://github.com/RUBi-ZA/MD-TASK/blob/mdm-task-web/data/pr1.pdb) from the data folder of the mdm-task-web branch. Also, VMD may have set the chain label to "X", in which case you have to specify "--chain X", because the default is set to chain A.

Kind regards,
Olivier

**Comment by cpayal** [comment]
Hi @oliserand . Thanks for your prompt replies, --chain X did the trick. 

Payal
