### ISSUE TITLE
Viewing residue networks on 3D protein structures

### ISSUE THREAD

**Issue by cpayal** [RUBi-ZA/MD-TASK#45]
Hi 

Is there a way to view the graphml/graph files overlay-ed on a pdb file ? I mean, if we want to visually present the network graphs for some of the selected domains of a protein, how can MD-TASK help?

Something like this:
![image](https://user-images.githubusercontent.com/30321815/199325266-0fa73fae-6596-479e-8d62-ce313f8e953c.png)

Apologies in advance for asking so many questions, but MDM-TASK Web has been really helpful!

Thanks
Payal

**Comment by oliserand** [comment]
Hi @cpayal. It sounds like a good idea, but we haven't explicitly implemented that, as our focus has mainly been on reporting  averaged network centrality calculations, mainly because proteins are always vibrating. One protein residue network can, and does differ from one time point to the next in a trajectory just because of this innate motion. We could implement something like that in the future, but we're not focused on that at the moment. Thanks for using MDM-TASK-web/MD-TASK.

**Comment by cpayal** [comment]
Thanks @oliserand , will look forward to it.
